import { Tool, PricingModel, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'text', name: 'Text & Writing', subCategories: ['Copywriting', 'Storytelling', 'Email Assistant', 'SEO'] },
  { id: 'image', name: 'Image Generation', subCategories: ['Art', 'Editing', 'Logos', 'Vectors'] },
  { id: 'video', name: 'Video & Animation', subCategories: ['Generation', 'Editing', 'Avatars', 'Dubbing'] },
  { id: 'audio', name: 'Audio & Speech', subCategories: ['Text to Speech', 'Music', 'Transcription', 'Voice Cloning'] },
  { id: 'code', name: 'Coding Assistant', subCategories: ['Code Generation', 'Debugging', 'Documentation', 'Terminal'] },
  { id: 'business', name: 'Business & Productivity', subCategories: ['Marketing', 'Finance', 'Meeting Assistants', 'Spreadsheets'] },
  { id: 'chat', name: 'Chatbots & Assistants', subCategories: ['General', 'Customer Support', 'Education', 'Search'] },
  { id: '3d', name: '3D & Design', subCategories: ['Modeling', 'Textures', 'Rendering'] },
  { id: 'dev', name: 'Developer Tools', subCategories: ['LLMs', 'Deployment', 'Testing'] },
  { id: 'research', name: 'Research & Science', subCategories: ['Academic', 'Papers', 'Citations', 'Discovery'] },
  { id: 'legal', name: 'Legal & Finance', subCategories: ['Contracts', 'Analysis', 'Accounting'] },
  { id: 'human', name: 'HR & Recruiting', subCategories: ['Resumes', 'Interviews', 'Sourcing'] },
];

export const MOCK_TOOLS: Tool[] = [
  // --- CHATBOTS & ASSISTANTS ---
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'A conversational AI model by OpenAI capable of understanding and generating human-like text.',
    websiteUrl: 'https://chat.openai.com',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Text & Writing'],
    features: ['Conversational Interface', 'Code Generation', 'Creative Writing', 'Plugin Support'],
    addedAt: '2022-11-30T00:00:00Z',
    popular: true,
  },
  {
    id: 'claude',
    name: 'Claude 3.5',
    description: 'A next-generation AI assistant built for work and trained to be safe, accurate, and secure.',
    websiteUrl: 'https://www.anthropic.com',
    imageUrl: 'https://logo.clearbit.com/anthropic.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Text & Writing', 'Coding Assistant'],
    features: ['Large Context Window', 'Safety Focused', 'Document Analysis', 'Coding'],
    addedAt: '2023-03-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google’s most capable and general model, built to be multimodal from the ground up.',
    websiteUrl: 'https://gemini.google.com',
    imageUrl: 'https://logo.clearbit.com/google.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Text & Writing', 'Coding Assistant'],
    features: ['Multimodal', 'Google Workspace Integration', 'Real-time Info', 'Reasoning'],
    addedAt: '2023-12-06T00:00:00Z',
    popular: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'Perplexity AI unlocks the power of knowledge with information discovery and sharing.',
    websiteUrl: 'https://www.perplexity.ai',
    imageUrl: 'https://logo.clearbit.com/perplexity.ai',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Business & Productivity', 'Research & Science'],
    features: ['Real-time Search', 'Source Citing', 'Follow-up Questions', 'Mobile App'],
    addedAt: '2023-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'mistral-le-chat',
    name: 'Le Chat Mistral',
    description: 'Conversational assistant by Mistral AI, offering high-performance open models.',
    websiteUrl: 'https://chat.mistral.ai',
    imageUrl: 'https://logo.clearbit.com/mistral.ai',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Open Weights', 'Multilingual', 'Reasoning', 'Coding'],
    addedAt: '2024-02-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    description: 'Your everyday AI companion. Integrated into Windows and Microsoft 365.',
    websiteUrl: 'https://copilot.microsoft.com',
    imageUrl: 'https://logo.clearbit.com/microsoft.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Business & Productivity', 'Image Generation'],
    features: ['GPT-4 Turbo', 'DALL-E 3', 'Web Search', '365 Integration'],
    addedAt: '2023-02-07T00:00:00Z',
    popular: true,
  },
  {
    id: 'poe',
    name: 'Poe',
    description: 'Poe lets you ask questions, get instant answers, and have back-and-forth conversations with AI.',
    websiteUrl: 'https://poe.com',
    imageUrl: 'https://logo.clearbit.com/poe.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants'],
    features: ['Access Multiple Models', 'Create Bots', 'Fast Interface', 'Mobile App'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'character-ai',
    name: 'Character.ai',
    description: 'Neural language model chatbot web application that can generate human-like text responses and participate in contextual conversation.',
    websiteUrl: 'https://beta.character.ai',
    imageUrl: 'https://logo.clearbit.com/character.ai',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Persona Creation', 'Roleplay', 'Creative Writing', 'Community Characters'],
    addedAt: '2023-05-01T00:00:00Z',
    popular: true,
  },
   {
    id: 'pi',
    name: 'Pi',
    description: 'A personalized AI, designed to be supportive, smart, and there for you anytime.',
    websiteUrl: 'https://pi.ai',
    imageUrl: 'https://logo.clearbit.com/inflection.ai',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Emotional Intelligence', 'Supportive', 'Conversational', 'Personal Advice'],
    addedAt: '2023-05-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'huggingchat',
    name: 'HuggingChat',
    description: 'Open source alternative to ChatGPT. Powered by Open Assistant and Llama models.',
    websiteUrl: 'https://huggingface.co/chat/',
    imageUrl: 'https://logo.clearbit.com/huggingface.co',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Open Source', 'Privacy Focused', 'Multiple Models', 'Web Search'],
    addedAt: '2023-04-25T00:00:00Z',
    popular: false,
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Incredibly fast AI inference. Experience near-instantaneous responses from LLMs.',
    websiteUrl: 'https://groq.com',
    imageUrl: 'https://logo.clearbit.com/groq.com',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants', 'Developer Tools'],
    features: ['Ultra Low Latency', 'LPU Inference Engine', 'Open Source Models', 'API Access'],
    addedAt: '2024-02-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'you-com',
    name: 'You.com',
    description: 'A search engine built on AI that summarizes the best parts of the internet for you.',
    websiteUrl: 'https://you.com',
    imageUrl: 'https://logo.clearbit.com/you.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Business & Productivity'],
    features: ['Private Search', 'YouChat', 'YouWrite', 'Code Generation'],
    addedAt: '2022-12-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'komo',
    name: 'Komo',
    description: 'An ad-free, AI-powered search engine that’s fast, private, and delivers the best answers.',
    websiteUrl: 'https://komo.ai',
    imageUrl: 'https://logo.clearbit.com/komo.ai',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Ad-free', 'Generative Search', 'Explore Mode', 'Community'],
    addedAt: '2023-01-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'phind',
    name: 'Phind',
    description: 'The AI search engine for developers.',
    websiteUrl: 'https://www.phind.com',
    imageUrl: 'https://logo.clearbit.com/phind.com',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants', 'Coding Assistant'],
    features: ['Developer Focused', 'Code Examples', 'Direct Answers', 'VS Code Extension'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'brave-leo',
    name: 'Brave Leo',
    description: 'A private AI smart assistant built into the Brave browser.',
    websiteUrl: 'https://brave.com/leo/',
    imageUrl: 'https://logo.clearbit.com/brave.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants'],
    features: ['Privacy First', 'Browser Integrated', 'Summarization', 'Q&A'],
    addedAt: '2023-11-02T00:00:00Z',
    popular: false,
  },
  {
    id: 'exa',
    name: 'Exa (Metaphor)',
    description: 'The search engine for LLMs. Designed to find the best content on the internet.',
    websiteUrl: 'https://exa.ai',
    imageUrl: 'https://logo.clearbit.com/exa.ai',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Developer Tools'],
    features: ['Neural Search', 'API', 'Content Discovery', 'Embeddings'],
    addedAt: '2023-08-01T00:00:00Z',
    popular: false,
  },

  // --- IMAGE GENERATION ---
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'An independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    websiteUrl: 'https://www.midjourney.com',
    imageUrl: 'https://logo.clearbit.com/midjourney.com',
    pricing: PricingModel.Paid,
    categories: ['Image Generation'],
    features: ['High Fidelity Art', 'Style Mimicry', 'Discord Interface', 'Upscaling'],
    addedAt: '2023-02-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'dalle3',
    name: 'DALL·E 3',
    description: 'AI system that can create realistic images and art from a description in natural language.',
    websiteUrl: 'https://openai.com/dall-e-3',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Paid,
    categories: ['Image Generation'],
    features: ['ChatGPT Integration', 'Prompt Adherence', 'High Resolution', 'Safety Guardrails'],
    addedAt: '2023-10-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'stability-ai',
    name: 'Stable Diffusion',
    description: 'A latent text-to-image diffusion model capable of generating photo-realistic images.',
    websiteUrl: 'https://stability.ai',
    imageUrl: 'https://logo.clearbit.com/stability.ai',
    pricing: PricingModel.Free,
    categories: ['Image Generation'],
    features: ['Open Source', 'Local Installation', 'Inpainting', 'Outpainting'],
    addedAt: '2022-08-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo.Ai',
    description: 'Create production-quality visual assets for your projects with unprecedented quality, speed, and style-consistency.',
    websiteUrl: 'https://leonardo.ai',
    imageUrl: 'https://logo.clearbit.com/leonardo.ai',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Game Assets', 'Model Training', 'Texture Generation', 'Canvas Editor'],
    addedAt: '2023-06-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: 'Generative AI made for creators. Use simple text prompts to generate images, text effects, and color palettes.',
    websiteUrl: 'https://www.adobe.com/sensei/generative-ai/firefly.html',
    imageUrl: 'https://logo.clearbit.com/adobe.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Commercial Safe', 'Photoshop Integration', 'Text Effects', 'Vector Recolor'],
    addedAt: '2023-04-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop',
    description: 'Create stunning visuals in seconds. The ultimate ecosystem of apps, plugins & resources for all creators.',
    websiteUrl: 'https://clipdrop.co',
    imageUrl: 'https://logo.clearbit.com/clipdrop.co',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Cleanup', 'Remove Background', 'Relight', 'Image Upscaler'],
    addedAt: '2023-05-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: 'A generative AI tool that helps users turn their creative ideas into beautiful images, with strong typography support.',
    websiteUrl: 'https://ideogram.ai',
    imageUrl: 'https://logo.clearbit.com/ideogram.ai',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation'],
    features: ['Typography', 'Logo Design', 'Text Rendering', 'Community Feed'],
    addedAt: '2023-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'playground-ai',
    name: 'Playground AI',
    description: 'A free-to-use online AI image creator. Use it to create art, social media posts, presentations, posters, videos, logos and more.',
    websiteUrl: 'https://playgroundai.com',
    imageUrl: 'https://logo.clearbit.com/playgroundai.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Canvas Editor', 'Filter Styles', 'Community', 'Mixed Image Editing'],
    addedAt: '2022-11-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'crayion',
    name: 'Craiyon',
    description: 'AI model that can draw images from any text prompt (formerly DALL-E mini).',
    websiteUrl: 'https://www.craiyon.com',
    imageUrl: 'https://logo.clearbit.com/craiyon.com',
    pricing: PricingModel.Free,
    categories: ['Image Generation'],
    features: ['Free to Use', 'Unlimited Generations', 'Print on Demand', 'Simple Interface'],
    addedAt: '2022-07-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'lexica',
    name: 'Lexica',
    description: 'The Stable Diffusion search engine and art gallery.',
    websiteUrl: 'https://lexica.art',
    imageUrl: 'https://logo.clearbit.com/lexica.art',
    pricing: PricingModel.Free,
    categories: ['Image Generation', 'Chatbots & Assistants'],
    features: ['Image Search', 'Prompt Inspiration', 'Aperture Model', 'High Quality'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'nightcafe',
    name: 'NightCafe',
    description: 'AI Art Generator App. Create amazing artworks using the power of Artificial Intelligence.',
    websiteUrl: 'https://creator.nightcafe.studio',
    imageUrl: 'https://logo.clearbit.com/nightcafe.studio',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation'],
    features: ['Multiple Models', 'Daily Challenges', 'Community', 'Style Transfer'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'civitai',
    name: 'Civitai',
    description: 'The only Model-sharing hub for the AI art generation community.',
    websiteUrl: 'https://civitai.com',
    imageUrl: 'https://logo.clearbit.com/civitai.com',
    pricing: PricingModel.Free,
    categories: ['Image Generation', 'Developer Tools'],
    features: ['Model Hosting', 'LoRA', 'Fine-tuned Checkpoints', 'Community Images'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'magnific-ai',
    name: 'Magnific AI',
    description: 'The most advanced AI upscaler and enhancer. It imagines details to create higher resolution images.',
    websiteUrl: 'https://magnific.ai',
    imageUrl: 'https://logo.clearbit.com/magnific.ai',
    pricing: PricingModel.Paid,
    categories: ['Image Generation', '3D & Design'],
    features: ['Upscaling', 'Hallucination Engine', 'Detail Enhancement', 'Style Transfer'],
    addedAt: '2023-11-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'krea-ai',
    name: 'Krea',
    description: 'Generative tools for creatives. Real-time generation and enhancement.',
    websiteUrl: 'https://www.krea.ai',
    imageUrl: 'https://logo.clearbit.com/krea.ai',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Real-time Canvas', 'Upscaling', 'Pattern Tool', 'Logo Illusion'],
    addedAt: '2023-12-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'photoroom',
    name: 'PhotoRoom',
    description: 'Create professional designs for free with our all-in-one creative photo editing platform.',
    websiteUrl: 'https://www.photoroom.com',
    imageUrl: 'https://logo.clearbit.com/photoroom.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', 'Business & Productivity'],
    features: ['Background Remover', 'Product Photography', 'Magic Edit', 'Mobile App'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'artbreeder',
    name: 'Artbreeder',
    description: 'Create characters, artworks and more with the power of AI. Blend images together.',
    websiteUrl: 'https://www.artbreeder.com',
    imageUrl: 'https://logo.clearbit.com/artbreeder.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation'],
    features: ['Gene Editing', 'Image Blending', 'Character Creation', 'Collage'],
    addedAt: '2022-06-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'stockimg',
    name: 'Stockimg AI',
    description: 'Generate stock images, wallpapers, logos, posters, illustrations, book covers and more.',
    websiteUrl: 'https://stockimg.ai',
    imageUrl: 'https://logo.clearbit.com/stockimg.ai',
    pricing: PricingModel.Paid,
    categories: ['Image Generation', 'Business & Productivity'],
    features: ['Stock Photos', 'Book Covers', 'Posters', 'Wallpapers'],
    addedAt: '2023-01-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'wombo-dream',
    name: 'WOMBO Dream',
    description: 'Create beautiful artwork using the power of AI. Enter a prompt, pick an art style and watch WOMBO Dream turn your idea into an AI-powered painting.',
    websiteUrl: 'https://dream.ai',
    imageUrl: 'https://logo.clearbit.com/dream.ai',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation'],
    features: ['Mobile App', 'Fast Generation', 'Art Styles', 'Community'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: true,
  },

  // --- VIDEO & ANIMATION ---
  {
    id: 'runway-ml',
    name: 'Runway',
    description: 'A multi-modal AI system that can generate novel videos with text, images, or video clips.',
    websiteUrl: 'https://runwayml.com',
    imageUrl: 'https://logo.clearbit.com/runwayml.com',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['Text to Video', 'Image to Video', 'Stylization', 'Inpainting'],
    addedAt: '2023-10-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'sora',
    name: 'Sora',
    description: 'OpenAI\'s text-to-video model capable of creating realistic and imaginative scenes from text instructions.',
    websiteUrl: 'https://openai.com/sora',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Contact,
    categories: ['Video & Animation'],
    features: ['Photorealistic', 'Complex Scenes', 'Physical Simulation', '60s Video Generation'],
    addedAt: '2024-02-15T00:00:00Z',
    popular: true,
  },
   {
    id: 'pika',
    name: 'Pika Labs',
    description: 'An idea-to-video platform that brings your creativity to motion.',
    websiteUrl: 'https://pika.art',
    imageUrl: 'https://logo.clearbit.com/pika.art',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Text to Video', 'Image Animation', 'Lip Sync', 'Modify Region'],
    addedAt: '2023-12-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'Create professional AI videos from text in 120 languages.',
    websiteUrl: 'https://www.synthesia.io',
    imageUrl: 'https://logo.clearbit.com/synthesia.io',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['AI Avatars', '120+ Languages', 'Screen Recorder', 'Custom Avatars'],
    addedAt: '2023-05-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'Next-gen video generation platform. Turn text into professional spokesman videos in minutes.',
    websiteUrl: 'https://www.heygen.com',
    imageUrl: 'https://logo.clearbit.com/heygen.com',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Talking Avatar', 'Video Translation', 'Voice Cloning', 'Templates'],
    addedAt: '2023-07-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    description: 'A next-generation video model for creating high-quality, realistic shots from text and images.',
    websiteUrl: 'https://lumalabs.ai/dream-machine',
    imageUrl: 'https://logo.clearbit.com/lumalabs.ai',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Text to Video', 'Image to Video', 'Physics Consistent', 'Fast Generation'],
    addedAt: '2024-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    description: 'High-quality video generation model capable of creating long-form, realistic videos.',
    websiteUrl: 'https://kling.kuaishou.com',
    imageUrl: 'https://logo.clearbit.com/kuaishou.com',
    pricing: PricingModel.Free,
    categories: ['Video & Animation'],
    features: ['Long Duration', 'High Motion', 'Realistic', 'Cinematic'],
    addedAt: '2024-06-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'd-id',
    name: 'D-ID',
    description: 'The #1 choice for AI-generated video creation. Create photorealistic videos from any face.',
    websiteUrl: 'https://www.d-id.com',
    imageUrl: 'https://logo.clearbit.com/d-id.com',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Live Portrait', 'Speaking Portrait', 'API Access', 'Real-time Streaming'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'kaiber',
    name: 'Kaiber',
    description: 'Video generation engine that allows users to create visual stories from their own images and audio.',
    websiteUrl: 'https://kaiber.ai',
    imageUrl: 'https://logo.clearbit.com/kaiber.ai',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['Audio Reactivity', 'Style Transfer', 'Animation', 'Spotify Canvas'],
    addedAt: '2023-06-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'A new kind of video editor for documents, slides, and podcasts.',
    websiteUrl: 'https://www.descript.com',
    imageUrl: 'https://logo.clearbit.com/descript.com',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Video & Animation'],
    features: ['Overdub', 'Filler Word Removal', 'Transcription-based Editing', 'Screen Recording'],
    addedAt: '2023-04-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'invideo',
    name: 'InVideo',
    description: 'Turn ideas into videos instantly with InVideo AI.',
    websiteUrl: 'https://invideo.io',
    imageUrl: 'https://logo.clearbit.com/invideo.io',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation', 'Business & Productivity'],
    features: ['Text to Video', 'Stock Media Library', 'Editor', 'Templates'],
    addedAt: '2023-08-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'wonder-dynamics',
    name: 'Wonder Dynamics',
    description: 'An AI tool that automatically animates, lights and composes CG characters into a live-action scene.',
    websiteUrl: 'https://wonderdynamics.com',
    imageUrl: 'https://logo.clearbit.com/wonderdynamics.com',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation', '3D & Design'],
    features: ['VFX', 'Motion Capture', 'Character Replacement', 'No Mocap Suits'],
    addedAt: '2023-05-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'fliki',
    name: 'Fliki',
    description: 'Turn text into videos with AI voices.',
    websiteUrl: 'https://fliki.ai',
    imageUrl: 'https://logo.clearbit.com/fliki.ai',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation', 'Audio & Speech'],
    features: ['Blog to Video', 'Text to Speech', 'Stock Library', 'Voice Cloning'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'opus-clip',
    name: 'Opus Clip',
    description: 'AI video repurposing tool that turns long videos into viral shorts.',
    websiteUrl: 'https://www.opus.pro',
    imageUrl: 'https://logo.clearbit.com/opus.pro',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation', 'Business & Productivity'],
    features: ['Auto Clipping', 'Virality Score', 'Captions', 'Face Tracking'],
    addedAt: '2023-05-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'veed-io',
    name: 'VEED.IO',
    description: 'Anyone can make a great video. Your audience prefers video. Veed makes it easy.',
    websiteUrl: 'https://www.veed.io',
    imageUrl: 'https://logo.clearbit.com/veed.io',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Auto Subtitles', 'Screen Recorder', 'AI Avatars', 'Eye Contact Correction'],
    addedAt: '2022-08-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'pictory',
    name: 'Pictory',
    description: 'Automatically create short, highly-sharable branded videos from your long form content.',
    websiteUrl: 'https://pictory.ai',
    imageUrl: 'https://logo.clearbit.com/pictory.ai',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation', 'Business & Productivity'],
    features: ['Script to Video', 'Blog to Video', 'Edit Video Using Text', 'Highlight Reels'],
    addedAt: '2023-01-05T00:00:00Z',
    popular: true,
  },
  {
    id: 'deepbrain',
    name: 'DeepBrain AI',
    description: 'Create realistic AI avatar videos with text-to-speech. Best for presentation and training videos.',
    websiteUrl: 'https://www.deepbrain.io',
    imageUrl: 'https://logo.clearbit.com/deepbrain.io',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['AI Studios', 'Custom Avatars', 'Multi-language', 'Templates'],
    addedAt: '2023-04-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'steve-ai',
    name: 'Steve AI',
    description: 'AI video maker for social media and content marketing. Create videos from text in seconds.',
    websiteUrl: 'https://www.steve.ai',
    imageUrl: 'https://logo.clearbit.com/steve.ai',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Animation', 'Live Action', 'Blog to Video', 'Voiceover'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: false,
  },

  // --- AUDIO & SPEECH ---
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'The most realistic and versatile AI speech software. Premier AI text-to-speech.',
    websiteUrl: 'https://elevenlabs.io',
    imageUrl: 'https://logo.clearbit.com/elevenlabs.io',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Voice Cloning', 'Text to Speech', 'Voice Design', 'Long-form Projects'],
    addedAt: '2023-08-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'suno',
    name: 'Suno AI',
    description: 'Suno is building a future where anyone can make great music.',
    websiteUrl: 'https://suno.ai',
    imageUrl: 'https://logo.clearbit.com/suno.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Video & Animation'],
    features: ['Music Generation', 'Text to Song', 'Instrumental', 'Vocals'],
    addedAt: '2024-01-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'udio',
    name: 'Udio',
    description: 'Make music in seconds. Udio allows you to generate complete songs with lyrics and vocals.',
    websiteUrl: 'https://www.udio.com',
    imageUrl: 'https://logo.clearbit.com/udio.com',
    pricing: PricingModel.Free,
    categories: ['Audio & Speech'],
    features: ['High Fidelity Music', 'Genre Mixing', 'Lyric Generation', 'Remixing'],
    addedAt: '2024-04-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'murf',
    name: 'Murf.ai',
    description: 'Go from text to speech with a versatile AI voice generator. AI voices for podcasts, videos, and professional presentations.',
    websiteUrl: 'https://murf.ai',
    imageUrl: 'https://logo.clearbit.com/murf.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Studio Quality Voices', 'Voice Cloning', 'Video Sync', 'Collaboration'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    description: 'Otter records meetings, takes notes in real time, and generates an automated summary.',
    websiteUrl: 'https://otter.ai',
    imageUrl: 'https://logo.clearbit.com/otter.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Business & Productivity'],
    features: ['Real-time Transcription', 'Meeting Summaries', 'Speaker Identification', 'Zoom Integration'],
    addedAt: '2023-03-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'lovo',
    name: 'Lovo.ai',
    description: 'Award-winning AI Voice Generator and Text to Speech software with 500+ voices in 100+ languages.',
    websiteUrl: 'https://lovo.ai',
    imageUrl: 'https://logo.clearbit.com/lovo.ai',
    pricing: PricingModel.Paid,
    categories: ['Audio & Speech'],
    features: ['Genny', 'Video Editing', 'Voice Cloning', 'Art Generator'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'playht',
    name: 'Play.ht',
    description: 'Generate realistic Text to Speech audio using AI. Convert text to audio for free.',
    websiteUrl: 'https://play.ht',
    imageUrl: 'https://logo.clearbit.com/play.ht',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Ultra Realistic', 'Voice Cloning', 'Podcast Hosting', 'SEO Audio'],
    addedAt: '2023-01-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'soundraw',
    name: 'Soundraw',
    description: 'AI music generator. Create and customize royalty-free music.',
    websiteUrl: 'https://soundraw.io',
    imageUrl: 'https://logo.clearbit.com/soundraw.io',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Royalty Free', 'Customizable', 'BGM', 'Commercial Use'],
    addedAt: '2022-12-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'boomy',
    name: 'Boomy',
    description: 'Make instant music with Artificial Intelligence and share it with the world.',
    websiteUrl: 'https://boomy.com',
    imageUrl: 'https://logo.clearbit.com/boomy.com',
    pricing: PricingModel.Free,
    categories: ['Audio & Speech'],
    features: ['Instant Music', 'Distribution', 'Royalties', 'Community'],
    addedAt: '2022-11-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'speechify',
    name: 'Speechify',
    description: 'The #1 Text to Speech reader. Power through docs, articles, PDFs, email - anything you read.',
    websiteUrl: 'https://speechify.com',
    imageUrl: 'https://logo.clearbit.com/speechify.com',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Listening Speed', 'Cross-Platform', 'Celebrity Voices', 'OCR'],
    addedAt: '2022-10-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'krisp',
    name: 'Krisp',
    description: 'AI Noise Cancellation. Krisp removes background noise, echoes, and more from your calls.',
    websiteUrl: 'https://krisp.ai',
    imageUrl: 'https://logo.clearbit.com/krisp.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Business & Productivity'],
    features: ['Noise Removal', 'Echo Cancellation', 'Meeting Transcription', 'Voice Clarity'],
    addedAt: '2022-04-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'cleanvoice',
    name: 'Cleanvoice',
    description: 'Stop wasting hours editing your podcast. Artificial intelligence removes filler sounds, stuttering and mouth sounds.',
    websiteUrl: 'https://cleanvoice.ai',
    imageUrl: 'https://logo.clearbit.com/cleanvoice.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Filler Remover', 'Stutter Remover', 'Timeline Export', 'Multitrack'],
    addedAt: '2023-01-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'podcastle',
    name: 'Podcastle',
    description: 'Studio quality recording, AI editing, and seamless exporting – all in a single web-based platform.',
    websiteUrl: 'https://podcastle.ai',
    imageUrl: 'https://logo.clearbit.com/podcastle.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Remote Recording', 'Magic Dust', 'Revoice', 'Text to Speech'],
    addedAt: '2023-02-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'adobe-podcast',
    name: 'Adobe Podcast',
    description: 'AI-powered audio recording and editing, all on the web.',
    websiteUrl: 'https://podcast.adobe.com',
    imageUrl: 'https://logo.clearbit.com/adobe.com',
    pricing: PricingModel.Free,
    categories: ['Audio & Speech'],
    features: ['Enhance Speech', 'Mic Check', 'Studio', 'Transcripts'],
    addedAt: '2023-05-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'voicemod',
    name: 'Voicemod',
    description: 'Free real-time voice changer and soundboard for PC and Mac.',
    websiteUrl: 'https://www.voicemod.net',
    imageUrl: 'https://logo.clearbit.com/voicemod.net',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Voice Changer', 'Soundboard', 'Real-time', 'Discord Compatible'],
    addedAt: '2022-08-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'riffusion',
    name: 'Riffusion',
    description: 'Real-time music generation with stable diffusion. Turn text prompts into audio.',
    websiteUrl: 'https://www.riffusion.com',
    imageUrl: 'https://logo.clearbit.com/riffusion.com',
    pricing: PricingModel.Free,
    categories: ['Audio & Speech'],
    features: ['Text to Music', 'Infinite Scroll', 'Spectrograms', 'Open Source'],
    addedAt: '2022-12-15T00:00:00Z',
    popular: false,
  },

  // --- CODING ASSISTANT ---
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'Your AI pair programmer. GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time.',
    websiteUrl: 'https://github.com/features/copilot',
    imageUrl: 'https://logo.clearbit.com/github.com',
    pricing: PricingModel.Paid,
    categories: ['Coding Assistant'],
    features: ['IDE Integration', 'Multi-language Support', 'Test Generation', 'Context Awareness'],
    addedAt: '2023-04-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'The AI-first Code Editor. Build software faster with an editor designed for pair-programming with AI.',
    websiteUrl: 'https://cursor.sh',
    imageUrl: 'https://logo.clearbit.com/cursor.sh',
    pricing: PricingModel.Freemium,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['VS Code Fork', 'Codebase Chat', 'Auto-debug', 'Command K'],
    addedAt: '2023-09-15T00:00:00Z',
    popular: true,
  },
   {
    id: 'replit',
    name: 'Replit AI',
    description: 'An AI-powered pair programmer built into the Replit online IDE.',
    websiteUrl: 'https://replit.com/ai',
    imageUrl: 'https://logo.clearbit.com/replit.com',
    pricing: PricingModel.Paid,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['Complete Code', 'Explain Code', 'Generate Code', 'Transform Code'],
    addedAt: '2023-01-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    description: 'AI assistant for software developers that anticipates your coding needs.',
    websiteUrl: 'https://www.tabnine.com',
    imageUrl: 'https://logo.clearbit.com/tabnine.com',
    pricing: PricingModel.Freemium,
    categories: ['Coding Assistant'],
    features: ['Whole-line Completion', 'Full-function Completion', 'Privacy Focused', 'Self-hosted option'],
    addedAt: '2022-06-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    description: 'The AI community building the future. Build, train and deploy state of the art models.',
    websiteUrl: 'https://huggingface.co',
    imageUrl: 'https://logo.clearbit.com/huggingface.co',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['Model Hosting', 'Datasets', 'Spaces', 'Community Driven'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'codeium',
    name: 'Codeium',
    description: 'Free AI Code Completion & Chat. An alternative to GitHub Copilot.',
    websiteUrl: 'https://codeium.com',
    imageUrl: 'https://logo.clearbit.com/codeium.com',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant'],
    features: ['Free for Individuals', '20+ Languages', 'IDE Extensions', 'Chat'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'blackbox',
    name: 'Blackbox AI',
    description: 'AI coding assistant to help developers code faster.',
    websiteUrl: 'https://www.useblackbox.io',
    imageUrl: 'https://logo.clearbit.com/useblackbox.io',
    pricing: PricingModel.Freemium,
    categories: ['Coding Assistant'],
    features: ['Code Search', 'Code Autocomplete', 'Extract Code from Video', 'Chat'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    description: 'Build applications faster with the ML-powered coding companion.',
    websiteUrl: 'https://aws.amazon.com/codewhisperer/',
    imageUrl: 'https://logo.clearbit.com/amazon.com',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant'],
    features: ['AWS Integration', 'Security Scans', 'Free Tier', 'Reference Tracking'],
    addedAt: '2023-04-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'devin',
    name: 'Devin (Cognition)',
    description: 'The first fully autonomous AI software engineer. Can plan and execute complex engineering tasks.',
    websiteUrl: 'https://www.cognition-labs.com/introducing-devin',
    imageUrl: 'https://logo.clearbit.com/cognition-labs.com',
    pricing: PricingModel.Contact,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['Autonomous Coding', 'Debugging', 'Deployment', 'Learning'],
    addedAt: '2024-03-12T00:00:00Z',
    popular: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek Coder',
    description: 'An open-source code model with advanced reasoning capabilities.',
    websiteUrl: 'https://deepseek.com',
    imageUrl: 'https://logo.clearbit.com/deepseek.com',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['Open Source', 'Long Context', 'Repo-level Understanding', 'FIM'],
    addedAt: '2024-01-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'warp',
    name: 'Warp',
    description: 'The terminal for the 21st century. Built with AI features like Warp AI.',
    websiteUrl: 'https://www.warp.dev',
    imageUrl: 'https://logo.clearbit.com/warp.dev',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['AI Command Search', 'Block-based', 'Collaborative', 'Fast Rust Build'],
    addedAt: '2022-08-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'bito',
    name: 'Bito',
    description: '10x faster coding with AI. Bito helps developers write code, understand syntax, write test cases.',
    websiteUrl: 'https://bito.ai',
    imageUrl: 'https://logo.clearbit.com/bito.ai',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant'],
    features: ['IDE Plugin', 'Chat', 'Diff View', 'Privacy'],
    addedAt: '2023-04-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'whatthediff',
    name: 'What The Diff',
    description: 'Your AI powered code review assistant. Save time on pull requests.',
    websiteUrl: 'https://whatthediff.ai',
    imageUrl: 'https://logo.clearbit.com/whatthediff.ai',
    pricing: PricingModel.Freemium,
    categories: ['Developer Tools'],
    features: ['PR Summaries', 'Refactoring Suggestions', 'Notification', 'GitHub Integration'],
    addedAt: '2022-11-20T00:00:00Z',
    popular: false,
  },

  // --- TEXT & WRITING ---
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'AI Copywriter that helps you write blog posts, social media posts, and marketing copy.',
    websiteUrl: 'https://www.jasper.ai',
    imageUrl: 'https://logo.clearbit.com/jasper.ai',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['50+ Templates', 'Boss Mode', 'Grammarly Integration', 'SEO Surfer Integration'],
    addedAt: '2023-03-05T00:00:00Z',
    popular: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    description: 'Chat by Copy.ai is an AI powered chat bot that helps you write content.',
    websiteUrl: 'https://www.copy.ai',
    imageUrl: 'https://logo.clearbit.com/copy.ai',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Blog Content', 'Social Media Posts', 'Email Marketing', '90+ Tools'],
    addedAt: '2023-01-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'Cloud-based typing assistant that reviews spelling, grammar, punctuation, clarity, and delivery mistakes.',
    websiteUrl: 'https://www.grammarly.com',
    imageUrl: 'https://logo.clearbit.com/grammarly.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Grammar Checking', 'Tone Detection', 'Plagiarism Checker', 'Generative AI'],
    addedAt: '2023-04-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    description: 'AI-powered paraphrasing tool that helps you rewrite and enhance any sentence, paragraph, or article.',
    websiteUrl: 'https://quillbot.com',
    imageUrl: 'https://logo.clearbit.com/quillbot.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing'],
    features: ['Paraphraser', 'Grammar Checker', 'Summarizer', 'Citation Generator'],
    addedAt: '2023-02-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    description: 'Best AI Writer for SEO Blogs, Facebook Ads, Google Ads, and Shopify Products.',
    websiteUrl: 'https://writesonic.com',
    imageUrl: 'https://logo.clearbit.com/writesonic.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['SEO Optimized', 'Article Writer', 'Landing Pages', 'Paraphrasing'],
    addedAt: '2023-03-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'Access the limitless power of AI, right inside Notion. Work faster. Write better.',
    websiteUrl: 'https://www.notion.so/product/ai',
    imageUrl: 'https://logo.clearbit.com/notion.so',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity', 'Text & Writing'],
    features: ['Summarization', 'Translation', 'Brainstorming', 'Editor Integration'],
    addedAt: '2023-02-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    description: 'The non-judgmental, always-there AI writing partner. Great for fiction and creative writing.',
    websiteUrl: 'https://www.sudowrite.com',
    imageUrl: 'https://logo.clearbit.com/sudowrite.com',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing'],
    features: ['Story Engine', 'Rewrite', 'Brainstorm', 'Character Generator'],
    addedAt: '2022-10-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'rytr',
    name: 'Rytr',
    description: 'An AI writing assistant that helps you create high-quality content, in just a few seconds, at a fraction of the cost.',
    websiteUrl: 'https://rytr.me',
    imageUrl: 'https://logo.clearbit.com/rytr.me',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing'],
    features: ['40+ Use Cases', '30+ Languages', 'SEO Analyzer', 'Chrome Extension'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'novelai',
    name: 'NovelAI',
    description: 'A monthly subscription service for AI-assisted authorship, storytelling, virtual companionship.',
    websiteUrl: 'https://novelai.net',
    imageUrl: 'https://logo.clearbit.com/novelai.net',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Chatbots & Assistants'],
    features: ['Storytelling', 'Image Generation', 'Text Adventure', 'Modules'],
    addedAt: '2022-08-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'anyword',
    name: 'Anyword',
    description: 'The AI writing platform for enterprise marketing teams that drives real results.',
    websiteUrl: 'https://anyword.com',
    imageUrl: 'https://logo.clearbit.com/anyword.com',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Predictive Performance', 'Brand Voice', 'Ad Copy', 'Website Copy'],
    addedAt: '2022-07-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    description: 'Your personal writing companion. Rewrite, summarize, and generate text.',
    websiteUrl: 'https://www.wordtune.com',
    imageUrl: 'https://logo.clearbit.com/wordtune.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing'],
    features: ['Rewrite', 'Casual/Formal Tone', 'Shorten/Expand', 'Spices'],
    addedAt: '2022-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'jenni-ai',
    name: 'Jenni AI',
    description: 'The ultimate AI writing assistant for research and academia.',
    websiteUrl: 'https://jenni.ai',
    imageUrl: 'https://logo.clearbit.com/jenni.ai',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing'],
    features: ['Autocomplete', 'Citations', 'Plagiarism Check', 'Academic Tone'],
    addedAt: '2023-01-05T00:00:00Z',
    popular: false,
  },
  {
    id: 'surfer-seo',
    name: 'Surfer SEO',
    description: 'Grow your organic traffic with the content optimization tool that ranks for you.',
    websiteUrl: 'https://surferseo.com',
    imageUrl: 'https://logo.clearbit.com/surferseo.com',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Content Editor', 'Keyword Research', 'Audit', 'SERP Analyzer'],
    addedAt: '2022-05-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'frase',
    name: 'Frase',
    description: 'Frase helps you research, write, and optimize high-quality SEO content in minutes.',
    websiteUrl: 'https://www.frase.io',
    imageUrl: 'https://logo.clearbit.com/frase.io',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Content Briefs', 'Content Writing', 'Optimization', 'Analytics'],
    addedAt: '2022-06-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'neuroflash',
    name: 'Neuroflash',
    description: 'Europe\'s No.1 AI content suite. Generate texts and images.',
    websiteUrl: 'https://neuroflash.com',
    imageUrl: 'https://logo.clearbit.com/neuroflash.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Image Generation'],
    features: ['German/English', 'Quality Check', 'Images', 'Templates'],
    addedAt: '2022-09-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'simplified',
    name: 'Simplified',
    description: 'The #1 AI writer for social media posts, blogs, and ads. All-in-one app.',
    websiteUrl: 'https://simplified.com',
    imageUrl: 'https://logo.clearbit.com/simplified.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Video & Animation', 'Image Generation'],
    features: ['Graphic Design', 'Video Editor', 'AI Writer', 'Social Publishing'],
    addedAt: '2022-08-15T00:00:00Z',
    popular: true,
  },

  // --- BUSINESS & PRODUCTIVITY ---
  {
    id: 'gamma',
    name: 'Gamma',
    description: 'A new medium for presenting ideas. Powered by AI. Create beautiful, engaging content with none of the formatting work.',
    websiteUrl: 'https://gamma.app',
    imageUrl: 'https://logo.clearbit.com/gamma.app',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', '3D & Design'],
    features: ['Presentation Generation', 'Document to Slides', 'Interactive Elements', 'Analytics'],
    addedAt: '2023-07-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'tome',
    name: 'Tome',
    description: 'The AI-powered storytelling format. Unlock your best work with Tome\'s AI-powered storytelling format.',
    websiteUrl: 'https://tome.app',
    imageUrl: 'https://logo.clearbit.com/tome.app',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Text & Writing'],
    features: ['Narrative Generation', 'Image Generation', 'Interactive Embeds', 'Mobile Friendly'],
    addedAt: '2023-03-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    description: 'Automate your meeting notes. Fireflies.ai helps your team record, transcribe, search, and analyze voice conversations.',
    websiteUrl: 'https://fireflies.ai',
    imageUrl: 'https://logo.clearbit.com/fireflies.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Audio & Speech'],
    features: ['Meeting Recorder', 'Transcription', 'AI Summaries', 'CRM Integrations'],
    addedAt: '2023-04-05T00:00:00Z',
    popular: true,
  },
  {
    id: 'mem',
    name: 'Mem',
    description: 'Mem is the self-organizing workspace for your team. It’s the world’s first AI-powered workspace.',
    websiteUrl: 'https://mem.ai',
    imageUrl: 'https://logo.clearbit.com/mem.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity'],
    features: ['Self-organizing', 'Knowledge Retrieval', 'Smart Write', 'Team Collaboration'],
    addedAt: '2023-05-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    description: 'Presentation software that designs for you. Create meaningful pitches and reports without putting other work on hold.',
    websiteUrl: 'https://www.beautiful.ai',
    imageUrl: 'https://logo.clearbit.com/beautiful.ai',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity', '3D & Design'],
    features: ['Smart Templates', 'Brand Controls', 'Analytics', 'Collaboration'],
    addedAt: '2023-01-25T00:00:00Z',
    popular: false,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Automation that moves you forward. Zapier connects your apps and services to automate repetitive tasks.',
    websiteUrl: 'https://zapier.com',
    imageUrl: 'https://logo.clearbit.com/zapier.com',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Developer Tools'],
    features: ['App Integration', 'No-code Automation', 'AI Actions', 'Canvas'],
    addedAt: '2023-06-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'canva-magic',
    name: 'Canva Magic',
    description: 'AI-powered design tools integrated into the Canva suite.',
    websiteUrl: 'https://www.canva.com',
    imageUrl: 'https://logo.clearbit.com/canva.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', 'Business & Productivity', '3D & Design'],
    features: ['Template Generation', 'Magic Edit', 'Text to Image', 'Brand Consistency'],
    addedAt: '2023-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'fathom',
    name: 'Fathom',
    description: 'Fathom records, transcribes, highlights, and summarizes your meetings so you can focus on the conversation.',
    websiteUrl: 'https://fathom.video',
    imageUrl: 'https://logo.clearbit.com/fathom.video',
    pricing: PricingModel.Free,
    categories: ['Business & Productivity', 'Audio & Speech'],
    features: ['Zoom/Google Meet/Teams', 'Auto Summaries', 'Share Clips', 'Sync to CRM'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'browse-ai',
    name: 'Browse AI',
    description: 'The easiest way to extract and monitor data from any website.',
    websiteUrl: 'https://www.browse.ai',
    imageUrl: 'https://logo.clearbit.com/browse.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Developer Tools'],
    features: ['Web Scraping', 'No Code', 'Monitoring', 'API'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'taskade',
    name: 'Taskade',
    description: 'AI-powered productivity. Outline tasks, notes, generate mind maps, and chat with AI.',
    websiteUrl: 'https://www.taskade.com',
    imageUrl: 'https://logo.clearbit.com/taskade.com',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity'],
    features: ['AI Assistant', 'Mind Maps', 'Project Management', 'Real-time Collab'],
    addedAt: '2022-12-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'gong',
    name: 'Gong',
    description: 'Gong analyzes customer-facing interactions to give you the insights you need to close more deals.',
    websiteUrl: 'https://www.gong.io',
    imageUrl: 'https://logo.clearbit.com/gong.io',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity'],
    features: ['Revenue Intelligence', 'Call Analysis', 'Deal Execution', 'Forecasting'],
    addedAt: '2022-09-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'superhuman',
    name: 'Superhuman AI',
    description: 'The fastest email experience ever made. Now with AI.',
    websiteUrl: 'https://superhuman.com',
    imageUrl: 'https://logo.clearbit.com/superhuman.com',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity', 'Text & Writing'],
    features: ['Email Summaries', 'Draft Responses', 'Split Inbox', 'Speed'],
    addedAt: '2023-05-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'motion',
    name: 'Motion',
    description: 'Motion uses AI to plan your day. It automatically schedules your tasks and meetings.',
    websiteUrl: 'https://www.usemotion.com',
    imageUrl: 'https://logo.clearbit.com/usemotion.com',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity'],
    features: ['Auto Scheduling', 'Project Management', 'Meeting Assistant', 'Calendar Sync'],
    addedAt: '2022-10-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'chatpdf',
    name: 'ChatPDF',
    description: 'Chat with any PDF. Join millions of students, researchers and professionals to instantly answer questions and understand research.',
    websiteUrl: 'https://www.chatpdf.com',
    imageUrl: 'https://logo.clearbit.com/chatpdf.com',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Text & Writing'],
    features: ['PDF Analysis', 'Q&A', 'Citations', 'Multi-language'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'humata',
    name: 'Humata',
    description: 'Humata is like GPT for your files. Ask questions and get answers from your documents instantly.',
    websiteUrl: 'https://www.humata.ai',
    imageUrl: 'https://logo.clearbit.com/humata.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Research & Science'],
    features: ['Document Analysis', 'Summarization', 'Secure', 'Unlimited Files'],
    addedAt: '2023-03-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'adcreative',
    name: 'AdCreative.ai',
    description: 'Generate conversion-focused ad creatives and social media post creatives in a matter of seconds.',
    websiteUrl: 'https://www.adcreative.ai',
    imageUrl: 'https://logo.clearbit.com/adcreative.ai',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity', 'Image Generation'],
    features: ['Ad Generation', 'Score Optimization', 'Brand Colors', 'Social Media'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'predis',
    name: 'Predis.ai',
    description: 'Create social media posts in seconds with AI. ChatGPT + Canva + Hootsuite = Predis.ai.',
    websiteUrl: 'https://predis.ai',
    imageUrl: 'https://logo.clearbit.com/predis.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Image Generation'],
    features: ['Post Generation', 'Scheduling', 'Video Maker', 'Hashtags'],
    addedAt: '2022-10-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'rewind',
    name: 'Rewind',
    description: 'Rewind records anything you’ve seen, said, or heard and makes it searchable.',
    websiteUrl: 'https://www.rewind.ai',
    imageUrl: 'https://logo.clearbit.com/rewind.ai',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity'],
    features: ['Screen Recording', 'Meeting Recorder', 'Local Storage', 'Searchable Memory'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'sanebox',
    name: 'SaneBox',
    description: 'AI email management tool. It identifies important emails and automatically organizes the rest.',
    websiteUrl: 'https://www.sanebox.com',
    imageUrl: 'https://logo.clearbit.com/sanebox.com',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity'],
    features: ['Email Filtering', 'SaneLater', 'No-Reply Tracking', 'Security'],
    addedAt: '2022-03-01T00:00:00Z',
    popular: false,
  },

  // --- OTHERS & 3D & DESIGN ---
  {
    id: 'lumalabs',
    name: 'Luma AI',
    description: 'Capture the world in lifelike 3D. Unmatched photorealism, reflections, and details.',
    websiteUrl: 'https://lumalabs.ai',
    imageUrl: 'https://logo.clearbit.com/lumalabs.ai',
    pricing: PricingModel.Free,
    categories: ['3D & Design', 'Video & Animation'],
    features: ['NeRF Technology', 'Video to 3D', 'Genie 3D Generator', 'Interactive Scenes'],
    addedAt: '2023-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'spline',
    name: 'Spline',
    description: 'Spline is a free 3D design tool with real-time collaboration to create web interactive experiences in the browser.',
    websiteUrl: 'https://spline.design',
    imageUrl: 'https://logo.clearbit.com/spline.design',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design'],
    features: ['AI Texture', 'AI Style Transfer', '3D Modeling', 'Web Embed'],
    addedAt: '2023-04-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'blockade-labs',
    name: 'Blockade Labs',
    description: 'Create 360° skybox worlds with AI. Skybox AI is a free tool for creating skybox environments.',
    websiteUrl: 'https://www.blockadelabs.com',
    imageUrl: 'https://logo.clearbit.com/blockadelabs.com',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design', 'Image Generation'],
    features: ['360 Panoramas', 'Skybox Generation', 'VR Ready', 'Sketch to Skybox'],
    addedAt: '2023-07-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'looka',
    name: 'Looka',
    description: 'Design a logo and build a brand you love with AI.',
    websiteUrl: 'https://looka.com',
    imageUrl: 'https://logo.clearbit.com/looka.com',
    pricing: PricingModel.Paid,
    categories: ['3D & Design', 'Image Generation'],
    features: ['Logo Maker', 'Brand Kit', 'Social Media Assets', 'Business Cards'],
    addedAt: '2022-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'namelix',
    name: 'Namelix',
    description: 'Business name generator. Generate a short, brandable business name using artificial intelligence.',
    websiteUrl: 'https://namelix.com',
    imageUrl: 'https://logo.clearbit.com/namelix.com',
    pricing: PricingModel.Free,
    categories: ['Business & Productivity'],
    features: ['Name Generation', 'Logo Ideas', 'Domain Check', 'Brandable Names'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'uizard',
    name: 'Uizard',
    description: 'Design wireframes, mockups, and prototypes in minutes. Scan sketches and transform them into designs.',
    websiteUrl: 'https://uizard.io',
    imageUrl: 'https://logo.clearbit.com/uizard.io',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design', 'Business & Productivity'],
    features: ['Sketch to Design', 'Screenshot to Design', 'Text to Design', 'Collaboration'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'galileo',
    name: 'Galileo AI',
    description: 'Copilot for interface design. Generate complex UI designs from simple text prompts.',
    websiteUrl: 'https://www.usegalileo.ai',
    imageUrl: 'https://logo.clearbit.com/usegalileo.ai',
    pricing: PricingModel.Paid,
    categories: ['3D & Design', 'Developer Tools'],
    features: ['Text to UI', 'Figma Export', 'Mobile & Web', 'High Fidelity'],
    addedAt: '2023-08-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'meshy',
    name: 'Meshy',
    description: 'Create 3D assets with AI. Text to 3D and Image to 3D in minutes.',
    websiteUrl: 'https://www.meshy.ai',
    imageUrl: 'https://logo.clearbit.com/meshy.ai',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design'],
    features: ['Text to 3D', 'Image to 3D', 'PBR Textures', 'Fast Generation'],
    addedAt: '2024-01-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'polycam',
    name: 'Polycam',
    description: 'The #1 3D scanner app for iPhone and Android. Capture the world in 3D.',
    websiteUrl: 'https://poly.cam',
    imageUrl: 'https://logo.clearbit.com/poly.cam',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design'],
    features: ['LiDAR Scanning', 'Photogrammetry', '360 Capture', 'Drone Mapping'],
    addedAt: '2022-03-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'csm',
    name: 'CSM',
    description: 'Cube to Space Model. Create 3D assets from video or images using AI.',
    websiteUrl: 'https://csm.ai',
    imageUrl: 'https://logo.clearbit.com/csm.ai',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design'],
    features: ['Video to 3D', 'Image to 3D', 'Game Assets', 'API'],
    addedAt: '2023-06-15T00:00:00Z',
    popular: false,
  },
  
  // --- DEVELOPER TOOLS & LLMs ---
  {
    id: 'langchain',
    name: 'LangChain',
    description: 'Building applications with LLMs through composability.',
    websiteUrl: 'https://langchain.com',
    imageUrl: 'https://logo.clearbit.com/langchain.com',
    pricing: PricingModel.Free,
    categories: ['Developer Tools'],
    features: ['Framework', 'Python & JS', 'Chains', 'Agents'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    description: 'Vector database for high-performance AI applications.',
    websiteUrl: 'https://www.pinecone.io',
    imageUrl: 'https://logo.clearbit.com/pinecone.io',
    pricing: PricingModel.Freemium,
    categories: ['Developer Tools'],
    features: ['Vector Search', 'Managed Service', 'Scalable', 'Low Latency'],
    addedAt: '2022-10-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'vercel-ai-sdk',
    name: 'Vercel AI SDK',
    description: 'The AI SDK is an open-source library for building AI-powered user interfaces.',
    websiteUrl: 'https://sdk.vercel.ai',
    imageUrl: 'https://logo.clearbit.com/vercel.com',
    pricing: PricingModel.Free,
    categories: ['Developer Tools'],
    features: ['Streaming', 'React Hooks', 'Svelte/Vue Support', 'Edge Compatible'],
    addedAt: '2023-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'openai-api',
    name: 'OpenAI API',
    description: 'Access OpenAI\'s powerful models like GPT-4 and DALL·E via a simple API.',
    websiteUrl: 'https://openai.com/api/',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Paid,
    categories: ['Developer Tools'],
    features: ['Text Completion', 'Embeddings', 'Fine-tuning', 'Function Calling'],
    addedAt: '2021-01-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Get up and running with large language models locally.',
    websiteUrl: 'https://ollama.com',
    imageUrl: 'https://logo.clearbit.com/ollama.com',
    pricing: PricingModel.Free,
    categories: ['Developer Tools'],
    features: ['Local LLMs', 'MacOS/Linux/Windows', 'Llama 3', 'API'],
    addedAt: '2023-07-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'supabase',
    name: 'Supabase Vector',
    description: 'The open source Firebase alternative. Build AI apps with pgvector.',
    websiteUrl: 'https://supabase.com/vector',
    imageUrl: 'https://logo.clearbit.com/supabase.com',
    pricing: PricingModel.Freemium,
    categories: ['Developer Tools'],
    features: ['Postgres', 'Vector Embeddings', 'Auth', 'Realtime'],
    addedAt: '2023-04-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run AI with an API. A community for sharing and running machine learning models.',
    websiteUrl: 'https://replicate.com',
    imageUrl: 'https://logo.clearbit.com/replicate.com',
    pricing: PricingModel.Paid,
    categories: ['Developer Tools', 'Image Generation'],
    features: ['Model Hosting', 'Open Source Models', 'Scalable API', 'Fine-tuning'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    description: 'Discover, download, and run local LLMs. Run any Llama, Mistral, Phill, Gamma model locally.',
    websiteUrl: 'https://lmstudio.ai',
    imageUrl: 'https://logo.clearbit.com/lmstudio.ai',
    pricing: PricingModel.Free,
    categories: ['Developer Tools'],
    features: ['Offline LLMs', 'Chat Interface', 'Local Server', 'Model Discovery'],
    addedAt: '2023-10-01T00:00:00Z',
    popular: true,
  },

  // --- RESEARCH & SCIENCE ---
  {
    id: 'consensus',
    name: 'Consensus',
    description: 'Search engine that uses AI to find answers in scientific research.',
    websiteUrl: 'https://consensus.app',
    imageUrl: 'https://logo.clearbit.com/consensus.app',
    pricing: PricingModel.Freemium,
    categories: ['Research & Science', 'Chatbots & Assistants'],
    features: ['Scientific Papers', 'Summarization', 'Citations', 'Trustworthy'],
    addedAt: '2022-12-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'elicit',
    name: 'Elicit',
    description: 'The AI Research Assistant. Analyze research papers at superhuman speed.',
    websiteUrl: 'https://elicit.com',
    imageUrl: 'https://logo.clearbit.com/elicit.com',
    pricing: PricingModel.Freemium,
    categories: ['Research & Science'],
    features: ['Literature Review', 'Paper Extraction', 'Synthesis', 'Search'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'scite',
    name: 'Scite',
    description: 'Assistant for researchers. Find, understand, and evaluate scientific research.',
    websiteUrl: 'https://scite.ai',
    imageUrl: 'https://logo.clearbit.com/scite.ai',
    pricing: PricingModel.Paid,
    categories: ['Research & Science'],
    features: ['Smart Citations', 'Fact Checking', 'Assistant', 'Dashboards'],
    addedAt: '2022-10-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'researchrabbit',
    name: 'ResearchRabbit',
    description: 'Reimagine literature search. A citation-based literature mapping tool.',
    websiteUrl: 'https://www.researchrabbit.ai',
    imageUrl: 'https://logo.clearbit.com/researchrabbit.ai',
    pricing: PricingModel.Free,
    categories: ['Research & Science'],
    features: ['Visual Mapping', 'Discovery', 'Alerts', 'Collaboration'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'scholarcy',
    name: 'Scholarcy',
    description: 'The AI-powered article summarizer. Read better, faster.',
    websiteUrl: 'https://www.scholarcy.com',
    imageUrl: 'https://logo.clearbit.com/scholarcy.com',
    pricing: PricingModel.Freemium,
    categories: ['Research & Science'],
    features: ['Summarizer', 'Flashcards', 'Reference Extraction', 'Library'],
    addedAt: '2022-08-01T00:00:00Z',
    popular: false,
  },

  // --- LEGAL & FINANCE ---
  {
    id: 'casetext',
    name: 'Casetext (CoCounsel)',
    description: 'The AI legal assistant. Do document review, legal research memos, deposition preparation, and contract analysis in minutes.',
    websiteUrl: 'https://casetext.com',
    imageUrl: 'https://logo.clearbit.com/casetext.com',
    pricing: PricingModel.Paid,
    categories: ['Legal & Finance'],
    features: ['Legal Research', 'Document Review', 'Contract Analysis', 'GPT-4 Powered'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'harvey',
    name: 'Harvey',
    description: 'Generative AI for elite law firms. Unprecedented legal reasoning and drafting capabilities.',
    websiteUrl: 'https://www.harvey.ai',
    imageUrl: 'https://logo.clearbit.com/harvey.ai',
    pricing: PricingModel.Contact,
    categories: ['Legal & Finance'],
    features: ['Legal LLM', 'Security First', 'Drafting', 'Analysis'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'truewind',
    name: 'Truewind',
    description: 'AI-powered bookkeeping and finance for startups.',
    websiteUrl: 'https://www.truewind.ai',
    imageUrl: 'https://logo.clearbit.com/truewind.ai',
    pricing: PricingModel.Paid,
    categories: ['Legal & Finance', 'Business & Productivity'],
    features: ['Bookkeeping', 'Monthly Close', 'Financial Models', 'Expert Support'],
    addedAt: '2023-02-15T00:00:00Z',
    popular: false,
  },

  // --- HR & RECRUITING ---
  {
    id: 'aragon',
    name: 'Aragon AI',
    description: 'Get professional AI headshots in minutes. No photographer needed.',
    websiteUrl: 'https://www.aragon.ai',
    imageUrl: 'https://logo.clearbit.com/aragon.ai',
    pricing: PricingModel.Paid,
    categories: ['HR & Recruiting', 'Image Generation'],
    features: ['Headshots', 'Realistic', 'Fast Turnaround', 'High Resolution'],
    addedAt: '2023-08-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'headshotpro',
    name: 'HeadshotPro',
    description: 'Professional business headshots for teams and individuals.',
    websiteUrl: 'https://www.headshotpro.com',
    imageUrl: 'https://logo.clearbit.com/headshotpro.com',
    pricing: PricingModel.Paid,
    categories: ['HR & Recruiting', 'Image Generation'],
    features: ['Team Headshots', 'Consistent Style', 'Background Options', '4K Quality'],
    addedAt: '2023-07-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'teal',
    name: 'Teal',
    description: 'The all-in-one AI career growth platform. Resume builder, job tracker, and more.',
    websiteUrl: 'https://www.tealhq.com',
    imageUrl: 'https://logo.clearbit.com/tealhq.com',
    pricing: PricingModel.Freemium,
    categories: ['HR & Recruiting'],
    features: ['Resume Builder', 'Job Tracker', 'Cover Letter AI', 'Keywords'],
    addedAt: '2022-10-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'metaview',
    name: 'Metaview',
    description: 'Automated interview notes for recruiting teams.',
    websiteUrl: 'https://www.metaview.ai',
    imageUrl: 'https://logo.clearbit.com/metaview.ai',
    pricing: PricingModel.Paid,
    categories: ['HR & Recruiting', 'Business & Productivity'],
    features: ['Interview Notes', 'ATS Integration', 'Insights', 'Time Saving'],
    addedAt: '2023-01-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'resumeworded',
    name: 'Resume Worded',
    description: 'Improve your resume and LinkedIn profile. Designed by top recruiters.',
    websiteUrl: 'https://resumeworded.com',
    imageUrl: 'https://logo.clearbit.com/resumeworded.com',
    pricing: PricingModel.Freemium,
    categories: ['HR & Recruiting'],
    features: ['Resume Score', 'LinkedIn Review', 'Templates', 'Targeting'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: true,
  }
];